title: "Samarth Pohekar"
description: "Exploring the World of Ethical Hacking & Bug Bounties"
author: "Samarth Pohekar"
baseurl: "samarth_pohekar/"
url: "https://samarthpohekar.github.io/"
theme: null
plugins:
   - jekyll-feed
include:
   - assets/css/style.css
   - images
   - static_files
   
permalink: /blog/:title/
about: "I’m Samarth Pohekar, a security enthusiast with a focus on ethical hacking, bug bounty hunting, and information security. I enjoy researching vulnerabilities and helping to secure applications and systems."


