title: "Samarth Pohekar"
description: "Exploring the World of Ethical Hacking & Bug Bounties"
author: "Samarth Pohekar"
baseurl: "samarth_pohekar/"
url: "https://samarthpohekar.github.io/"
theme: null
plugins:
   - jekyll-feed
include:
   - assets/css/style.css

